version: '3'

services:
  tile-server:
    build: ./docker/tile-server/
    volumes:
    - var-run-renderd:/var/run/renderd
    - ./docker/volumes/tiles:/var/lib/mod_tile
    ports:
    - 80:80
    links:
    - tile-renderer
  tile-renderer:
    build: ./docker/tile-renderer/
    environment:
      POSTGRES_HOST: map-database
      POSTGRES_DB: map
      POSTGRES_USER: map
      POSTGRES_PASSWORD: map
    volumes:
    - var-run-renderd:/var/run/renderd
    - ./docker/volumes/tiles:/var/lib/mod_tile
    links:
    - map-database
  tile-prerenderer:
    build: ./docker/tile-renderer/
    command: ["render_list", "--map", "default", "--min-zoom", "1", "--max-zoom", "10", "--all"]
    volumes:
    - var-run-renderd:/var/run/renderd
    - ./docker/volumes/tiles:/var/lib/mod_tile
    links:
    - tile-renderer
  map-database:
    build: ./docker/map-database/
    environment:
      POSTGRES_PASSWORD: password
    volumes:
    - map-database-data:/var/lib/postgresql/data
    - ./docker/map-database/initdb:/docker-entrypoint-initdb.d
  map-data-util:
    build: ./docker/map-data-util
    environment:
      POSTGRES_HOST: map-database
      POSTGRES_ADMIN_USER: postgres
      POSTGRES_ADMIN_PASSWORD: password
      POSTGRES_MAP_DB: map
      POSTGRES_MAP_USER: map
      POSTGRES_MAP_PASSWORD: map
    volumes:
    - ./docker/volumes/map_data:/map_data
    links:
    - map-database

volumes:
  var-run-renderd:
  map-database-data:
