version: '3'

services:
  tile-server:
    build: ./docker/tile-server/
    command: apachectl -D FOREGROUND
    volumes:
    - ./docker/volumes/tiles:/var/lib/mod_tile
    ports:
    - 80:80
    links:
    - tile-renderer
  tile-renderer:
    build: ./docker/tile-renderer/
    command: renderd -f -c /renderd.conf
    volumes:
    - ./docker/volumes/tiles:/var/lib/mod_tile
    - ./docker/tile-renderer/renderd.conf:/renderd.conf
    ports:
    - 7654:7654
    links:
    - map-database
  map-database:
    build: ./docker/map-database/
    environment:
      POSTGRES_DB: gis
      POSTGRES_USER: renderaccount
      POSTGRES_PASSWORD: renderaccount
    volumes:
    - map-database-data:/var/lib/postgresql/data
    - ./docker/map-database/initdb:/docker-entrypoint-initdb.d
    ports:
    - 5432:5432
  osm2pgsql:
    build: ./docker/osm2pgsql
    volumes:
    - ./docker/volumes/map_data:/map_data
    links:
    - map-database

volumes:
  map-database-data:
