version: '3'

services:
  tile-server:
    build: ./docker/tile-server/
    volumes:
    - var-run-renderd:/var/run/renderd
    - ./docker/volumes/tiles:/var/lib/mod_tile
    ports:
    - 80:80
    links:
    - tile-renderer
  tile-renderer:
    build: ./docker/tile-renderer/
    environment:
      POSTGRES_HOST: map-database
      POSTGRES_DB: gis
      POSTGRES_USER: renderaccount
      POSTGRES_PASSWORD: renderaccount
    volumes:
    - var-run-renderd:/var/run/renderd
    - ./docker/volumes/tiles:/var/lib/mod_tile
    links:
    - map-database
  map-database:
    build: ./docker/map-database/
    environment:
      POSTGRES_DB: gis
      POSTGRES_USER: renderaccount
      POSTGRES_PASSWORD: renderaccount
    volumes:
    - map-database-data:/var/lib/postgresql/data
    - ./docker/map-database/initdb:/docker-entrypoint-initdb.d
    ports:
    - 5432:5432
  osm2pgsql:
    build: ./docker/osm2pgsql
    volumes:
    - ./docker/volumes/map_data:/map_data
    links:
    - map-database

volumes:
  var-run-renderd:
  map-database-data:
