#!/usr/bin/env bash

set -eu

mkdir -p /map_data
cd /map_data
wget http://download.geofabrik.de/asia/azerbaijan-latest.osm.pbf
PGPASSWORD=$POSTGRES_MAP_PASSWORD osm2pgsql --host $POSTGRES_HOST --username $POSTGRES_MAP_USER \
  -d $POSTGRES_MAP_DB --create --slim -G --hstore \
  --tag-transform-script /openstreetmap-carto/openstreetmap-carto.lua \
  -C 2500 --number-processes 4 -S /openstreetmap-carto/openstreetmap-carto.style \
  /map_data/azerbaijan-latest.osm.pbf
